title : Youssef Ahmed
logo : assets/youssefahmed.jfif
#description : A fast-learning computer science student with a strong knowledge of Python and Machine Learning models, passionate about gaining experience in various technological fields, seeking an opportunity to expand my knowledge in a professional and diverse environment.
#show download : ture
theme: jekyll-theme-minimal
