title : Youssef Ahmed
logo : assets/youssefahmed.jfif
#description : A fast-learning computer science student ,seeking an opportunity to expand my knowledge in a professional and diverse environment.
#show download : ture
theme: jekyll-theme-minimal
